// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SalesforceContactTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "./src/test/resources/drivers/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public void login() {
        driver.get("https://jpcorp-dev-ed.lightning.force.com");
        driver.manage().window().setSize(new Dimension(968, 680));
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("username")).sendKeys(vars.get("username").toString());
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys(vars.get("password").toString());
        driver.findElement(By.id("Login")).click();
    }

    @Test
    public void logout() {
        {
            WebElement element = driver.findElement(By.cssSelector(".photoContainer"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".profileTrigger > .uiImage")).click();
        driver.findElement(By.linkText("Log Out")).click();
    }

    @Test
    public void createContact() {
        vars.put("username", "juampi7237@gmail.com");
        vars.put("password", "JP123456jp");
        vars.put("contactName", "New contact");
        login();
        driver.findElement(By.cssSelector(".slds-icon-waffle")).click();
        driver.findElement(By.xpath("//input[@placeholder='Search apps and items...']")).click();
        driver.findElement(By.xpath("//input[@placeholder='Search apps and items...']")).sendKeys("Contacts");
        driver.findElement(By.xpath("//a[@data-label='Contacts']")).click();
        driver.findElement(By.xpath("//div[contains(text(),'New')]")).click();
        driver.findElement(By.xpath("//input[@name='lastName']")).click();
        driver.findElement(By.xpath("//input[@name='lastName']")).sendKeys(vars.get("contactName").toString());
        driver.findElement(By.name("SaveEdit")).click();
        assertThat(driver.findElement(By.cssSelector(".slds-theme--success")).getText(), is("success\\\\nContact \\\"vars.get(\"contactName\").toString()\\\" was created.\\\\nClose"));
        logout();
    }

    @Test
    public void createContactAll() {
        vars.put("username", "juampi7237@gmail.com");
        vars.put("password", "JP123456jp");
        vars.put("lastName", "lastname");
        vars.put("firstName", "firstName");
        login();
        driver.findElement(By.cssSelector(".slds-icon-waffle")).click();
        driver.findElement(By.xpath("//input[@placeholder='Search apps and items...']")).click();
        driver.findElement(By.xpath("//input[@placeholder='Search apps and items...']")).sendKeys("Contacts");
        driver.findElement(By.xpath("//a[@data-label='Contacts']")).click();
        driver.findElement(By.xpath("//div[contains(text(),'New')]")).click();
        driver.findElement(By.name("salutation")).click();
        driver.findElement(By.xpath("//input[@name='firstName']")).click();
        driver.findElement(By.xpath("//input[@name='firstName']")).sendKeys(vars.get("firstName").toString());
        driver.findElement(By.xpath("//input[@name='lastName']")).click();
        driver.findElement(By.xpath("//input[@name='lastName']")).sendKeys(vars.get("lastName").toString());
        driver.findElement(By.xpath("//input[@placeholder='Search Accounts...']")).click();
        driver.findElement(By.xpath("(//ul[@role=\"group\"]//lightning-base-combobox-item[contains(@class, 'slds-listbox__option')])[1]")).click();
        driver.findElement(By.name("Title")).click();
        driver.findElement(By.name("Title")).sendKeys("Title");
        driver.findElement(By.name("Department")).click();
        driver.findElement(By.name("Department")).sendKeys("Department");
        driver.findElement(By.name("Birthdate")).click();
        driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(4) > .slds-day")).click();
        driver.findElement(By.name("Phone")).click();
        driver.findElement(By.name("Phone")).sendKeys("Phone");
        driver.findElement(By.name("HomePhone")).click();
        driver.findElement(By.name("HomePhone")).sendKeys("HomePhone");
        driver.findElement(By.name("MobilePhone")).click();
        driver.findElement(By.name("MobilePhone")).sendKeys("MobilePhone");
        driver.findElement(By.name("OtherPhone")).click();
        driver.findElement(By.name("OtherPhone")).sendKeys("OtherPhone");
        driver.findElement(By.name("Fax")).click();
        driver.findElement(By.name("Fax")).sendKeys("Fax");
        driver.findElement(By.name("Email")).click();
        driver.findElement(By.name("Email")).sendKeys("email@gmail.com");
        driver.findElement(By.name("AssistantName")).click();
        driver.findElement(By.name("AssistantName")).sendKeys("AssistantName");
        driver.findElement(By.name("AssistantPhone")).click();
        driver.findElement(By.name("AssistantPhone")).sendKeys("AssistantPhone");
        driver.findElement(By.xpath("(//textarea[@name='street'])[1]")).click();
        driver.findElement(By.xpath("(//textarea[@name='street'])[1]")).sendKeys("strret1");
        driver.findElement(By.xpath("(//input[@name='postalCode'])[1]")).click();
        driver.findElement(By.xpath("(//input[@name='postalCode'])[1]")).sendKeys("postalcode");
        driver.findElement(By.xpath("(//input[@name='city'])[1]")).click();
        driver.findElement(By.xpath("(//input[@name='city'])[1]")).sendKeys("city");
        driver.findElement(By.xpath("(//input[@name='province'])[1]")).click();
        driver.findElement(By.xpath("(//input[@name='province'])[1]")).sendKeys("Province");
        driver.findElement(By.xpath("(//input[@name='country'])[1]")).click();
        driver.findElement(By.xpath("(//input[@name='country'])[1]")).sendKeys("country");
        driver.findElement(By.xpath("(//textarea[@name='street'])[2]")).click();
        driver.findElement(By.xpath("(//textarea[@name='street'])[2]")).sendKeys("strret2");
        driver.findElement(By.xpath("(//input[@name='postalCode'])[2]")).click();
        driver.findElement(By.xpath("(//input[@name='postalCode'])[2]")).sendKeys("postalcode2");
        driver.findElement(By.xpath("(//input[@name='city'])[2]")).click();
        driver.findElement(By.xpath("(//input[@name='city'])[2]")).sendKeys("city2");
        driver.findElement(By.xpath("(//input[@name='province'])[2]")).click();
        driver.findElement(By.xpath("(//input[@name='province'])[2]")).sendKeys("Province2");
        driver.findElement(By.xpath("(//input[@name='country'])[2]")).click();
        driver.findElement(By.xpath("(//input[@name='country'])[2]")).sendKeys("country2");
        driver.findElement(By.name("Languages__c")).click();
        driver.findElement(By.name("Languages__c")).sendKeys("Languages__c");
        driver.findElement(By.xpath("(//force-record-layout-section//textarea)[3]")).click();
        driver.findElement(By.xpath("(//force-record-layout-section//textarea)[3]")).sendKeys("description");
        driver.findElement(By.name("SaveEdit")).click();
        assertThat(driver.findElement(By.cssSelector(".custom-truncate")).getText(), is("vars.get(\"firstName\").toString() ${lastName}"));
        logout();
    }
}
